"""Rollback-only PostgreSQL tests: no real PACS upload or patient data changes."""
import io
from pathlib import Path
from unittest.mock import MagicMock, patch
from fastapi import UploadFile, HTTPException
import pydicom
from tests.test_imaging_history import ImagingHistoryTests
from tests.test_imaging_orders import xray_bytes
from tests.test_radiology_clarifications import BorrowConnection
from routers import imaging_orders as orders
from radiology_ai.services import study_store


class MultiStudyTests(ImagingHistoryTests):
    def setUp(self):
        super().setUp()
        self.cur.execute('''
            ALTER TABLE radiology_scan ALTER COLUMN scan_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100);
            ALTER TABLE radiology_scan ADD COLUMN patient_id bigint, ADD COLUMN patient_code text,
                ADD COLUMN original_patient_id text, ADD COLUMN display_study_id text,
                ADD COLUMN target integer, ADD COLUMN probability float,
                ADD COLUMN priority text, ADD COLUMN opacity_detected boolean, ADD COLUMN combined_status text,
                ADD COLUMN annotated_image text, ADD COLUMN clinical_summary text, ADD COLUMN assessment text,
                ADD COLUMN recommended_action text, ADD COLUMN findings text, ADD COLUMN viewed boolean,
                ADD COLUMN viewed_at timestamptz;
            CREATE TABLE dim_generated_discharge_summaries(patient_id bigint,primary_consultant text,summary_id bigint);
            CREATE TABLE dim_admission_inputs(patient_id bigint,attending_doctor text,admission_id bigint);
            CREATE TABLE appointments(patient_id bigint,doctor_id bigint);
            CREATE TABLE pre_admissions(patient_id bigint,doctor_id bigint);
        ''')
        patcher = patch.object(study_store, 'get_connection', return_value=BorrowConnection(self.conn))
        patcher.start()
        self.addCleanup(patcher.stop)

    def combined(self):
        payload = self.payload()
        payload['examination'] = 'Chest X-ray PA + AP'
        response = self.call('POST', json=payload)
        self.assertEqual(response.status_code, 201, response.text)
        self.assertEqual(self.call('POST', json=payload).json(), response.json())
        return response.json()

    def content(self, projection):
        ds = pydicom.dcmread(io.BytesIO(xray_bytes('PAT100')))
        ds.ViewPosition = projection
        output = io.BytesIO()
        ds.save_as(output, enforce_file_format=True)
        return output.getvalue()

    def upload(self, order, projection, content=None):
        content = content or self.content(projection)
        def pacs(method, path, **kwargs):
            response = MagicMock()
            response.json.return_value = [] if path == '/tools/find' else {
                'ID': projection + '-instance', 'ParentStudy': projection + '-study'}
            return response
        with patch.object(orders, '_request', side_effect=pacs):
            return orders.upload_order(order['order_id'], UploadFile(io.BytesIO(content)),
                                       {'user_id': 3}, False, projection)

    def result(self, uid):
        return {'source': {'study_instance_uid': uid}, 'localization': {'opacity_detected': False},
                'images': {'original': uid, 'annotated': 'overlay-' + uid},
                'interpretation': {'summary': 'AI summary ' + uid}, 'analyzed_at': '2026-09-24T00:00:00Z'}

    def test_two_studies_independent_results_reviews_and_readiness(self):
        order = self.combined()
        self.assertEqual({s['projection'] for s in order['studies']}, {'PA', 'AP'})
        pa_bytes = self.content('PA')
        first = self.upload(order, 'PA', pa_bytes)
        self.assertEqual(first['status'], 'Requested')
        pa_uid = next(s['study_instance_uid'] for s in first['studies'] if s['projection'] == 'PA')
        pa = self.result(pa_uid)
        study_store.save_study(pa)
        self.assertEqual(study_store.list_studies(), [])
        self.assertIsNone(study_store.get_study(order['order_id']))
        second = self.upload(order, 'AP')
        self.assertEqual(second['status'], 'Uploaded')
        ap_uid = next(s['study_instance_uid'] for s in second['studies'] if s['projection'] == 'AP')
        ap = self.result(ap_uid)
        study_store.save_study(ap)
        self.assertNotEqual(pa['study_id'], ap['study_id'])
        self.assertEqual(len(study_store.list_studies(doctor_user_id=1)), 2)
        study_store.update_review_status(pa['study_id'], 'Confirmed', '2026-09-24T01:00:00Z', 'Reader One', 'PA confirmed')
        self.assertEqual(study_store.get_study(ap['study_id'])['review_status'], 'Pending Review')
        study_store.save_study(self.result(pa_uid))
        self.assertEqual(study_store.get_study(pa['study_id'])['scan_report'], 'PA confirmed')
        self.assertEqual(study_store.get_study(ap['study_id'])['images']['original'], ap_uid)
        self.assertEqual(self.upload(order, 'PA', pa_bytes)['status'], 'Uploaded')
        history = self.call('GET', f"/{order['order_id']}/history").json()
        self.assertEqual(len(history['studies']), 1)
        self.assertEqual(len(history['studies'][0]['studies']), 2)

    def test_reject_wrong_view_missing_view_duplicate_uid_and_replacement(self):
        order = self.combined()
        for content in [self.content('AP'), xray_bytes('PAT100')]:
            with self.assertRaises(HTTPException) as error:
                self.upload(order, 'PA', content)
            self.assertEqual(error.exception.status_code, 422)
        pa = self.content('PA')
        self.upload(order, 'PA', pa)
        with self.assertRaises(HTTPException) as error:
            self.upload(order, 'PA')
        self.assertEqual(error.exception.status_code, 409)
        ds = pydicom.dcmread(io.BytesIO(pa))
        ds.ViewPosition = 'AP'
        output = io.BytesIO()
        ds.save_as(output, enforce_file_format=True)
        with self.assertRaises(HTTPException) as error:
            self.upload(order, 'AP', output.getvalue())
        self.assertEqual(error.exception.status_code, 409)

    def test_pacs_failure_can_retry_same_file(self):
        order = self.combined()
        content = self.content('PA')
        def pacs(method, path, **kwargs):
            if path == '/instances':
                raise orders.OrthancError('Unavailable')
            result = MagicMock()
            result.json.return_value = []
            return result
        with patch.object(orders, '_request', side_effect=pacs), self.assertRaises(HTTPException) as error:
            orders.upload_order(order['order_id'], UploadFile(io.BytesIO(content)), {'user_id': 3}, False, 'PA')
        self.assertEqual(error.exception.status_code, 502)
        self.assertEqual(self.upload(order, 'PA', content)['studies'][0]['status'], 'Uploaded')

    def test_migration_rerun_preserves_two_studies(self):
        order = self.combined()
        migration = (Path(__file__).parents[1] / 'db/migrations/006_multi_study_orders.sql').read_text()
        self.cur.execute(migration.replace('BEGIN;', '').replace('COMMIT;', ''))
        self.cur.execute('SELECT count(*) FROM radiology_order_studies WHERE order_id=%s', (order['order_id'],))
        self.assertEqual(self.cur.fetchone()[0], 2)

    def test_watcher_retries_failed_view_without_reanalyzing_completed_view(self):
        from radiology_ai.services import pacs_watcher_service as watcher
        order = self.combined()
        self.upload(order, 'PA')
        uploaded = self.upload(order, 'AP')
        studies = [{'study_id': s['projection'] + '-study', 'study_instance_uid': s['study_instance_uid']}
                   for s in uploaded['studies']]
        calls = []
        def analyze(sid, _stamp):
            calls.append(sid)
            if sid == 'AP-study' and calls.count(sid) == 1:
                raise RuntimeError('Temporary model failure')
            uid = next(s['study_instance_uid'] for s in studies if s['study_id'] == sid)
            study_store.save_study(self.result(uid))
        with patch.object(watcher, '_states', {}), patch.object(watcher, 'get_studies', return_value=studies), patch.object(watcher.logger, 'exception'):
            watcher.scan_once(analyze)
            self.assertEqual(study_store.list_studies(), [])
            self.assertEqual(watcher.get_status('AP-study')['analysis_status'], 'FAILED')
            watcher.scan_once(analyze)
            self.assertEqual(len(study_store.list_studies()), 2)
            self.assertEqual(calls.count('PA-study'), 1)
            self.assertEqual(calls.count('AP-study'), 2)

    def test_clarification_snapshot_contains_both_reports_and_requires_both_reviews(self):
        from routers.radiology_clarifications import order_report, report_fingerprint
        rows = [dict(scan_id=1, scan_report='PA report', reviewed_by='Reader', reviewed_at='2026-09-24',
                     dl_response='{"projection":"PA"}'),
                dict(scan_id=2, scan_report='AP report', reviewed_by=None, reviewed_at=None,
                     dl_response='{"projection":"AP"}')]
        first = order_report(rows, 2)
        self.assertIsNone(first['reviewed_at'])
        self.assertIn('PA: PA report', first['scan_report'])
        self.assertIn('AP: AP report', first['scan_report'])
        rows[1].update(reviewed_at='2026-09-25', reviewed_by='Reader')
        second = order_report(rows, 2)
        self.assertIsNotNone(second['reviewed_at'])
        self.assertNotEqual(report_fingerprint(first), report_fingerprint(second))
