CREATE TABLE IF NOT EXISTS knowledge_documents (
    id BIGSERIAL PRIMARY KEY,
    document_code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    document_type VARCHAR(50) NOT NULL CHECK (document_type IN ('HOSPITAL_PROFILE', 'DEPARTMENT', 'DOCTOR_INFORMATION', 'OPD_TIMING', 'FAQ', 'APPOINTMENT_POLICY', 'CANCELLATION_POLICY', 'RESCHEDULING_POLICY', 'ADMISSION', 'PRE_ADMISSION', 'EMERGENCY', 'HOSPITAL_SERVICE')),
    source VARCHAR(255),
    content TEXT NOT NULL,
    language VARCHAR(20) NOT NULL CHECK (language IN ('ENGLISH', 'TAMIL', 'HINDI', 'TELUGU', 'MALAYALAM', 'KANNADA', 'URDU')),
    version VARCHAR(10) NOT NULL DEFAULT '1.0',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_knowledge_docs_code ON knowledge_documents(document_code);
CREATE INDEX IF NOT EXISTS idx_knowledge_docs_type ON knowledge_documents(document_type);
