st CT = ['Appointment reminder', 'Queue update', 'Diagnostic preparation', 'Report ready', 'Discharge status', 'Billing update', 'Follow-up reminder', 'Feedback request'];
  S.comms = Array.from({ length: 200 }, (_, i) => { const p = pick(S.patients); return { id: 'MSG-' + (60000 + i), patientId: p.id, patient: p.name, ts: -int(0, 3) * 1440 + int(420, 1320), channel: pick(['WhatsApp', 'SMS', 'Mobile push', 'Voice', 'Email']), type: pick(CT), lang: p.lang === 'Tamil' ? 'TA' : 'EN', status: pick(['Delivered', 'Read', 'Read', 'Failed']), agent: 'AG-02' }; });
  [[-5 * 1440 + 1152, 'WhatsApp', 'Appointment confirmed', 'EN'], [-3 * 1440 + 630, 'Mobile push', 'Pre-registration complete', 'EN'], [-3 * 1440 + 680, 'WhatsApp', 'Insurance preauth approved ₹1,95,000', 'TA'], [552, 'Mobile push', 'Discharge planning has started', 'TA'], [670, 'WhatsApp', 'Discharge status · expected ~4:20 PM', 'TA']].forEach(([ts, channel, type, lang], i) => S.comms.push({ id: 'MSG-6099' + i, patientId: D.kavitha.uhid, patient: 'Kavitha Raman', ts, channel, type, lang, status: 'Read', agent: 'AG-02' }));
  // Agents 21 with builder config
  S.agents = D.agents.concat(AGENT_EXTRA).map(a => { const type = TYPE_OF(a.name); const tools = TOOLS.filter(() => rnd() < 0.4).map(t => ({ tool: t, read: true, write: /Messaging|Notification|Scheduling|Housekeeping|Document/.test(t), approval: /Billing|Insurance|EMR/.test(t), enabled: true })); const vparts = a.v.split('.'); const versions = [];
    for (let i = 1; i <= +vparts[0]; i++) versions.push({ v: i + '.0.0', created: (1 + i * 20) + ' days ago', author: pick(['AI Engineering', 'Ops Product', 'Clinical Informatics']), changes: pick(['Initial release', 'Added escalation rules', 'New tool: Housekeeping', 'Prompt safety hardening', 'Tamil output']), score: int(84, 97), approval: 'Approved · AI Governance Committee', published: i === +vparts[0] });
    if (versions.length) versions[versions.length - 1].v = a.v;
    return { ...a, type, humanApproval: a.tier === 'High' ? 'Required' : a.tier === 'Medium' ? 'Selective' : 'None', status: a.status === 'Active' ? 'Published' : a.status === 'Suspended' ? 'Disabled' : a.status, statusNote: a.status, config: { identity: { nameEn: a.name, nameTa: a.name === 'Discharge Orchestration Agent' ? 'டிஸ்சார்ஜ் ஒருங்கிணைப்பு முகவர்' : '—', purpose: a.name === 'Discharge Orchestration Agent' ? 'Coordinate inpatient discharge dependencies, identify blockers, predict readiness, initiate parallel operational tasks and escalate exceptions while keeping clinical and billing approval with authorized humans.' : 'Assist ' + a.owner + ' with ' + a.name.replace(' Agent', '').toLowerCase() + ' tasks under human oversight.', type }, instructions: { objective: 'Reduce turnaround and manual coordination for ' + a.owner + '.', system: 'You are the Hospital ' + a.name + '. Operate only on the patient/workflow context provided. Cite sources. Never diagnose, prescribe, triage or sign.', rules: 'Use Tamil when the patient language is Tamil. Prefer structured outputs. Log every tool call.', safety: 'Refuse clinical interpretation. Do not release bills, sign documents or submit to insurers. Mask PHI outside the care team.', escalation: 'Escalate to the human owner when confidence < 70%, a tool fails twice, or an SLA is breached.', refusal: '"I don\'t have enough verified information to answer this safely." then route to a human.' }, knowledge: D.knowledgeDocs.filter(() => rnd() < 0.4).map(k => k.title), tools, memory: { session: 'On · 30 min', patient: 'Encounter-scoped', workflow: 'On', retention: '90 days (audit) · 0 days (conversation)', sensitive: 'No free-text PHI stored' }, access: { roles: a.owner + ', Hospital Management', departments: 'All wards', patients: 'Care-team relationship required', scopes: 'Operational + financial (no clinical write)', env: 'Production' }, model: { model: 'meridian-llm-large', temperature: 0.2, tokens: 8000, fallback: 'meridian-llm-small', latency: '< 3 s p50', cost: '₹' + int(4, 60) + ' / run' }, versions } , evals: [] }; });
  // Knowledge 100
  S.knowledge = D.knowledgeDocs.map((k, i) => ({ ...k, id: 'KD-' + pad(i + 1) })); const KT = ['Infection Control Policy', 'Consent Procedure', 'Blood Transfusion SOP', 'Fall Prevention Protocol', 'Pressure Injury Protocol', 'Code Blue Procedure', 'Bed Management Policy', 'Visitor Policy', 'Radiology Safety Manual', 'Lab Sample Handling', 'Pharmacy Formulary', 'Oxygen Therapy SOP', 'Pain Management Guide', 'Insurance Desk Handbook', 'Cashless Process Guide', 'Estimate Counselling SOP', 'Refund Policy', 'Grievance Redressal Policy', 'Leave Policy Annex', 'Payroll FAQ'];
  for (let i = S.knowledge.length; i < 100; i++) S.knowledge.push({ id: 'KD-' + pad(i + 1), title: pick(KT) + ' ' + pick(['', 'Annex A', 'Part 2', 'Ward edition']).trim(), dept: pick(DEPTS.concat(['HR', 'Finance', 'Quality', 'Nursing'])), v: int(1, 4) + '.' + int(0, 5), eff: pad(int(1, 28)) + ' ' + pick(['Jan', 'Mar', 'May', 'Jul']) + ' 2026', r